# Autoruns while startup
exec swayidle -w \
         timeout 300 'swaylock -L -e -u -f -i /home/kelt/Pictures/Wallpapers/not_loaded.png' \
         timeout 350 'swaymsg "output * power off"' resume 'swaymsg "output * power on"' \
         before-sleep 'swaylock -L -e -u -f -i /home/kelt/Pictures/Wallpapers/not_loaded.png'
exec swaync
exec $polkit
exec $nightlight

