# Input devices
input "type:keyboard" {
     xkb_layout us,ua(homophonic)
     xkb_options grp:win_space_toggle
     repeat_delay 300
     repeat_rate 30
}
input "type:touchpad" {
    dwt disabled
    tap enabled
    middle_emulation enabled
}
input "type:pointer" {
    accel_profile flat
}

