# Some Sway configs
default_border pixel 1
client.focused #fbf1c7 #282828 #ebdbb2 #928374 #fbf1c7
gaps inner 0
gaps outer 0
focus_follows_mouse no
floating_modifier $mod normal
focus_on_window_activation focus

# Cursor theme
seat seat0 xcursor_theme "Capitaine Cursors (Gruvbox)"

# Bar
bar {
	swaybar_command waybar
	position top
	hidden_state hide
	mode hide
	modifier $mod+Alt
}
