# Window rules
for_window {
  [window_type="dialog"] floating enable
  [window_type="utility"] floating enable
  [window_type="toolbar"] floating enabler_window 
  [window_type="splash"] floating enable r_window 

  # Float Thunar dialogs based on their title
  [app_id="thunar" title="Rename"] floating enable
  [app_id="thunar" title="File Operation Progress"] floating enable
  [app_id="thunar" title="Properties"] floating enable
}
